#配置文件版本，请勿修改
configVersion: '1'

#未登录提示
kickMessage: '请修改配置文件!'

#IP错误提示，%UserIp%将被替换为用户的IP地址
ipErrorMessage: '请修改配置文件!您的IP是：%UserIp%'

#未知错误提示，%UserIp%将被替换为用户的IP地址
unkonwErrorMessage: '请修改配置文件!您的IP是：%UserIp%'

#服务端访问密码
serverPassword: ''

#正确登录的返回信息
allowJoinResult: 'yes'

#IP错误时的返回信息
badIpResult: 'badip'

#网页验证端URL，一般为logincheck.php
checkUrl: ''

#网页端接收服务器发送的玩家ip页面的URL，一般为sendip.php
sendIpUrl: ''

#查询方式(可以使用GET或者POST，填写post使用POST，填写其他则使用GET)
queryMode: 'GET'

#加密模式(验证用户是否已经登录时使用的加密方式，填写MD5按照默认加密方式，填写其他则不加密)
encodeMode: 'MD5'

#回环地址免登录(当ip为127.0.0.1时跳过登录检查，默认不跳过)
skipOnLoopBackAddress: false

#内网地址免登录(当ip为内网ip时跳过登录检查，默认不跳过)
skipOnSiteLocalAddress: false

#是否使用BeeLogin客户端专用mod(默认不使用，请根据客户端是否装有BeeLoginUImod来填写此项)
usingBeeLoginUIMod: false

#使用mod时的超时时间(默认为20tick,20tick=1秒)
timeOutLimited: 20

#使用mod时的超时提示
timeOutMessage: '登录超时'